### ISSUE TITLE
Did anyone install MedS-Ins model successfully?

### ISSUE THREAD

**Issue by MXC66ai** [MAGIC-AI4Med/MedS-Ins#1]
Did anyone install MedS-Ins model successfully? I couldn't find the requirements.txt file, and the hugging face only found the MedS-Ins dataset without the model

**Comment by Henrychur** [comment]
Hello,

The model weights are available here: https://huggingface.co/Henrychur/MMedS-Llama-3-8B.

For installation, you just need to install latest PyTorch and Transformers.

Thanks for your feedback! We'll be adding detailed installation instructions to the README soon.
