### ISSUE TITLE
我想请教一下，论文中的MedS-Bench与MedS-Ins数据来源是否相同？我注意到MedS-Ins的数据量明显大于MedS-Bench，请问这方面有什么考虑吗？

### ISSUE THREAD

**Issue by rosechen2016** [MAGIC-AI4Med/MedS-Ins#4]

**Comment by Henrychur** [comment]
您好！
是的，数据来源是相同的。关于MedS-Ins的数据量明显大于MedS-Bench，首先并不是所有在MedS-Ins的任务都出现在MedS-Bench中，这是因为我们为每个类型的任务选择了部分认为重要的任务。其次，对于我们自己合成的数据，按照9：1的比例划分的，对于有自己固定train-dev-test划分的数据集，我们采用了官方的划分，将test部分划到了MedS-Bench中，train划到了MedS-Ins中。如果还有进一步的问题，欢迎进一步交流~
